/*
 * This source file was generated by the Gradle 'init' task
 */
package com.system.batch;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class KillBatchSystemApplicationTest {
    @Test void appHasAGreeting() {
        KillBatchSystemApplication classUnderTest = new KillBatchSystemApplication();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
